name: GitHub Actions Demo
run-name: GitHub Actions Demo

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 原始碼
        uses: actions/checkout@v3

      - name: 安裝 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝相依套件
        run: |
          pip install tinydb
          pip install pytest

      - name: 執行 pytest 測試
        run: |
          pytest -v
